name: Run Python Script

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'   # 오전 8시 (KST)
    - cron: '0 3 * * *'   # 오후 12시 (KST)
    - cron: '0 9 * * *'   # 오후 6시 (KST)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Secret 및 환경변수 사용
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: |
          set -e
          python rss-scrapper.py