name: Data Collection and Processing

on:
  push:
    branches: [main]
  schedule:
    # Run every 3 hours
    - cron: '0 */3 * * *'     # Data collection
    - cron: '0 23 * * *'      # Newsletter (8:00 AM KST)

jobs:
  data-collection:
    name: Data Collection and Processing
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || github.event.schedule == '0 */3 * * *'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data collection and processing
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          set -e
          python rss-scrapper.py
          python data-engineer-rss-scrapper.py

  send-newsletter:
    name: Send Newsletter
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && github.event.schedule == '0 23 * * *'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send newsletter email
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python news_data_processor.py
          python newsletter_sender.py
          python data_engineer_news_data_processor.py
